# Generated by Django 4.0.4 on 2022-05-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='cell_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Cell Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text='Email address of the teacher.', max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text='Enter the first name of the teacher.', max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(help_text='Enter the last name of the teacher.', max_length=50, null=True, verbose_name='Last Name'),
        ),
    ]
