# Generated by Django 4.0.4 on 2022-05-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_class_class_uid_and_more'),
        ('teacher', '0003_alter_teacher_cell_number_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='attendance.class'),
        ),
    ]
