databases:
  - name: Database
    databaseName: students_attendance_db_up8o
    user: students_attendance_user

services:
  - type: web
    name: STUDENTSATTENDANCE
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn STUDENTSATTENDANCE.config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
