# Generated by Django 4.0.4 on 2022-05-08 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('class_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Class Unique Identifier')),
                ('grade', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], default='1', help_text='Select grade of class.', max_length=2, verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ('grade',),
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('attendance_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Attendance Unique Identifier')),
                ('attendance_created', models.DateTimeField(auto_now_add=True, verbose_name='Attendance Creation Date')),
                ('attendance_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('attendance', models.CharField(choices=[('P', 'Present'), ('UNEX', 'SC-UNEX ( Unexcused / Unverified'), ('ETRD', 'SC-ETRD ( Excused Tardy )'), ('UTRD', 'SC-UTRD ( Unexcused Tardy )'), ('VTP', 'SC-VTP ( Virtual Present Code )')], default='P', max_length=4, verbose_name='Attendance')),
            ],
        ),
    ]
