# Generated by Django 4.0 on 2022-05-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade',), 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
