# Generated by Django 4.0.4 on 2022-05-08 22:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('student_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Student Unique Identifier')),
                ('first_name', models.CharField(help_text="Enter student's first name", max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text="Enter student's middle name if any", max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text="Enter student's last name", max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(help_text="Pick the student's date of birth", verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('race', models.CharField(choices=[('W', 'White'), ('B', 'Black / African American'), ('AIN', 'American Indian / Alaska Native'), ('A', 'Asian'), ('H', 'Native Hawaiian / Other Pacific Islander'), ('O', 'Some Other Race')], default='W', max_length=3, verbose_name='Race')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, verbose_name="Student's ID")),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name="Student's Address")),
                ('father_name', models.CharField(blank=True, help_text="Enter the name of the student's father.", max_length=100, null=True, verbose_name="Father's Name")),
                ('father_contact', models.CharField(blank=True, help_text='Enter the contact of the father ( phone )', max_length=20, null=True, verbose_name="Father's Contact")),
                ('mother_name', models.CharField(blank=True, help_text="Enter the name of the student's mother.", max_length=100, null=True, verbose_name="Mother's Name")),
                ('mother_contact', models.CharField(blank=True, help_text='Enter the contact of the mother ( phone )', max_length=20, null=True, verbose_name="Mother's Contact")),
                ('guardian_name', models.CharField(blank=True, help_text='In the absence of either parents, fill in the name of the current guardian of student.', max_length=100, null=True, verbose_name='Name of Guardian')),
                ('guardian_email', models.EmailField(blank=True, help_text='Enter the email address of any of the guardians of the student.', max_length=255, null=True, verbose_name="Guardian's Email")),
                ('home_phone', models.CharField(max_length=50, verbose_name='Home Phone')),
                ('grade', models.ForeignKey(default='1', help_text='What class is this student?', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ('first_name',),
            },
        ),
    ]
