# Generated by Django 4.0.4 on 2022-04-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default='1', help_text='What class is this student?', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.class'),
        ),
    ]
