# Generated by Django 4.0.4 on 2022-04-29 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Student Unique Identifier'),
        ),
    ]
