# Generated by Django 4.0.4 on 2022-04-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_student_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', help_text="Enter student's last name", max_length=50, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, help_text="Enter student's middle name if any", max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
