# Generated by Django 4.0.4 on 2022-04-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_created', models.DateTimeField(auto_now_add=True, verbose_name='Attendance Creation Date')),
                ('attendance_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Modified')),
                ('attendance', models.CharField(choices=[('P', 'Present'), ('UNEX', 'SC-UNEX ( Unexcused / Unverified'), ('ETRD', 'SC-ETRD ( Excused Tardy )'), ('UTRD', 'SC-UTRD ( Unexcused Tardy )'), ('VTP', 'SC-VTP ( Virtual Present Code )')], default='P', max_length=4, verbose_name='Attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.student')),
            ],
        ),
    ]
