# Generated by Django 4.0.4 on 2022-05-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_uid',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='attendance_uid',
        ),
    ]
