# Generated by Django 4.0.4 on 2022-04-30 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='attendance_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Attendance Unique Identifier'),
        ),
    ]
