# Generated by Django 4.0.4 on 2022-04-30 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentattendance_attendance_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Class Unique Identifier'),
        ),
    ]
