# Generated by Django 4.0.4 on 2022-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_class_class_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_created',
            field=models.DateField(auto_now_add=True, verbose_name='Attendance Creation Date'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Modified'),
        ),
    ]
