# Generated by Django 4.0.4 on 2022-05-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_grade'),
        ('student', '0002_remove_student_student_uid'),
        ('attendance', '0005_rename_attendance_created_studentattendance_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Grade',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade',), 'verbose_name': 'Grade', 'verbose_name_plural': 'Gradees'},
        ),
    ]
